### ISSUE TITLE
False (repository) positive Springer

### ISSUE THREAD

**Issue by michaelavoigt** [ourresearch/oadoi#125]
for 10.1007/s10198-018-0990-2 Unpaywall flags the publishers version as repository version - but url_for_landing_page clearly links to publisher's website... should not be flagged with oa_status: "green" since there's no repository version available. and probably not as "is_oa: true" either (unfortunately)

(cf. http://api.unpaywall.org/v2/10.1007/s10198-018-0990-2 as of March 16th)

{
best_oa_location: {
endpoint_id: "8da803012a7aa37d990",
evidence: "oa repository (via OAI-PMH title and first author match)",
host_type: "repository",
is_best: true,
license: null,
pmh_id: "oai:RePEc:spr:eujhec:v:20:y:2019:i:1:d:10.1007_s10198-018-0990-2",
repository_institution: null,
updated: "2019-12-03T07:00:12.003233",
url: "http://link.springer.com/10.1007/s10198-018-0990-2",
url_for_landing_page: "http://link.springer.com/10.1007/s10198-018-0990-2",
url_for_pdf: null,
version: "submittedVersion",
},
data_standard: 2,
doi: "10.1007/s10198-018-0990-2",
doi_url: "https://doi.org/10.1007/s10198-018-0990-2",
genre: "journal-article",
has_repository_copy: true,
is_oa: true,
is_paratext: false,
journal_is_in_doaj: false,
journal_is_oa: false,
journal_issn_l: "1618-7598",
journal_issns: "1618-7598,1618-7601",
journal_name: "The European Journal of Health Economics",
oa_locations: [
{
endpoint_id: "8da803012a7aa37d990",
evidence: "oa repository (via OAI-PMH title and first author match)",
host_type: "repository",
is_best: true,
license: null,
pmh_id: "oai:RePEc:spr:eujhec:v:20:y:2019:i:1:d:10.1007_s10198-018-0990-2",
repository_institution: null,
updated: "2019-12-03T07:00:12.003233",
url: "http://link.springer.com/10.1007/s10198-018-0990-2",
url_for_landing_page: "http://link.springer.com/10.1007/s10198-018-0990-2",
url_for_pdf: null,
version: "submittedVersion",
}
],
oa_status: "green",
published_date: "2018-07-02",
publisher: "Springer Science and Business Media LLC",
title: "Trends and regional variation in rates of orthopaedic surgery in Germany: the impact of competition",
updated: "2020-03-03T08:52:03.840570",
year: 2018,
z_authors: [
{
ORCID: "http://orcid.org/0000-0001-6883-1554",
authenticated-orcid: false,
family: "Baier",
given: "Natalie",
sequence: "first",
},
{
family: "Sax",
given: "Lisa-Marie",
sequence: "additional",
},
{
family: "Sundmacher",
given: "Leonie",
sequence: "additional",
},
],
}

**Comment by richard-orr** [comment]
We evaluate repository and publisher pages differently, so this happens sometimes when a repository record links back to the publisher page. We fixed whatever difference was letting this one through and the link was removed March 26.

Sorry for the slow reply. We moved issue tracking to support@unpaywall.org and I don't check here often.
